apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmbasics.resourceName" . }}-deployment     # helmbasics.resourceName   is a name of reusable named template in which we define labels
  labels:
  {{- include "helmbasics.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
     {{- include "helmbasics.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
       {{- include "helmbasics.labels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: ghcr.io/stacksimplify/kubenginx:4.0.0
        ports:
        - containerPort: 80
